module.exports = {
  projects: [
    '<rootDir>/apps/todos-app',
    '<rootDir>/apps/api',
    '<rootDir>/libs/shared/models',
    '<rootDir>/libs/todos-app/feature-todos',
    '<rootDir>/libs/todos-app/ui-header',
    '<rootDir>/libs/todos-app/ui-material',
    '<rootDir>/libs/todos-app/ui-todos-list',
    '<rootDir>/libs/todos-app/data-access-todos',
    '<rootDir>/libs/todos-app/ui-todo-form',
    '<rootDir>/libs/api/todos',
    '<rootDir>/libs/todos-app/feature-todo-detail',
    '<rootDir>/libs/todos-app/ui-todo-detail-form',
    '<rootDir>/libs/todos-app/data-access-todo-detail',
    '<rootDir>/libs/api/todo-detail',
    '<rootDir>/libs/api/shared/data',
    '<rootDir>/libs/todos-app/util-auto-unsubscribe',
    '<rootDir>/libs/todos-app/ui-loading-indicator',
    '<rootDir>/libs/todos-app/ui-new-todo-dialog',
  ],
};
